hydra:
  job:
    chdir: true

profile: false

seed: 42

flow:
  # - pretrain
  - evaluator
  # - optimization
  # - sweep
  # - plot_param
  # - data_collect

data:
  dataset: fashion_mnist
  train_batch_size: 512
  test_batch_size: 16
  num_workers: 0
  train_ratio: 0.8

training:
  devices: 
    - cuda:0
  cnn_epochs: 10 # mnist: 10, cifar10: 30
  cnn_lr: 0.05 # mnist: 0.05, cifar10: 0.01
  hd_epochs: 10 # mnist: 10, cifar10: 15
  hd_lr: 1.0
  num_tests: 5

hardware:
  type: cimloop
  # type: analytical
  noise: true
  temperature: 300
  power: energy
  cnn: true

params_prop:
  - name: hd_dim
    type: choice
    values:
      # - 512
      - 1024
      - 2048
      - 4096
      - 8192
    value_type: int
  # - name: hd_dim
  #   type: fixed
  #   value: 2048
  #   value_type: int
  # - name: npe1
  #   type: range
  #   bounds: 
  #     - 8
  #     - 256
  #   value_type: int
  # - name: npe1
  #   type: fixed
  #   value: 128
  #   value_type: int
  # - name: npe2
  #   type: range
  #   bounds: 
  #     - 8
  #     - 256
  #   value_type: int
  # - name: npe2
  #   type: fixed
  #   value: 128
  #   value_type: int
  - name: reram_size
    type: choice
    values:
      # - 64
      - 128
      - 256
    value_type: int
  # - name: reram_size
  #   type: fixed
  #   value: 64
  #   value_type: int
  # - name: f1
  #   type: choice
  #   values:
  #     - 28
  #     - 56
  #     - 49
  #     # - 11
  #     # - 17
  #     # - 33
  #     # - 51
  #     # - 3
  #     # - 9
  #   value_type: int
  # - name: d1
  #   type: choice
  #   values:
  #     - 32
  #     - 64
  #     - 128
  #   value_type: int
  # - name: kron
  #   type: choice
  #   values:
  #     - true
  #     - false
  #   value_type: bool
  - name: frequency
    type: fixed
    value: 1e8
    value_type: int
  # - name: frequency
  #   type: choice
  #   values:
  #     - 1e8
  #     - 2e8
  #     - 3e8
  #     - 4e8
  #     - 5e8
  #     - 6e8
  #     - 7e8
  #     - 8e8
  #     - 9e8
  #     - 1e9
  #   value_type: int
  - name: out_channels_1
    type: choice
    values:
      - 4
      - 8
      - 16
    value_type: int
  - name: kernel_size_1
    type: choice
    values:
      - 3
      - 5
    value_type: int
  - name: stride_1
    type: range
    bounds:
      - 1
      - 2
    value_type: int
  - name: padding_1
    type: fixed
    value: 0
    value_type: int
  - name: dilation_1
    type: fixed
    value: 1
    value_type: int
  - name: out_channels_2
    type: choice
    values:
      - 8
      - 16
      - 32
    value_type: int
  - name: kernel_size_2
    type: choice
    values:
      - 3
      - 5
    value_type: int
  - name: stride_2
    type: range
    bounds:
      - 1
      - 2
    value_type: int
  - name: padding_2
    type: fixed
    value: 0
    value_type: int
  - name: dilation_2
    type: fixed
    value: 1
    value_type: int
  - name: cnn_x_dim_1
    type: choice
    values:
      - 8
      - 16
    value_type: int
  - name: cnn_y_dim_1
    type: choice
    values:
      - 8
      - 16
    value_type: int
  - name: cnn_x_dim_2
    type: choice
    values:
      - 8
      - 16
    value_type: int
  - name: cnn_y_dim_2
    type: choice
    values:
      - 8
      - 16
    value_type: int
  - name: encoder_x_dim
    type: choice
    values:
      - 8
      - 16
    value_type: int
  - name: encoder_y_dim
    type: choice
    values:
      - 8
      - 16
    value_type: int
  - name: inner_dim
    type: choice
    values:
      - 1024
      - 2048
      - 4096
    value_type: int

metrics:
  - accuracy
  - power
  - performance
  - area

pretrain:
  epochs: 100

optimization:
  num_trials: 60
  num_epochs: 60
  acqf: qExpectedHypervolumeImprovement
  metrics_file: cifar10_random
  constrained: false
  preferenced: true
  constraints:
    accuracy: 0.3
    power: 0.2
    performance: 0.2
    area: 0.2
  preference:
    accuracy: 0.4
    power: 0.2
    performance: 0.2
    area: 0.2

sweep:
  interval: 5
  metrics_file: sweep
  accept_rate: 0.02

evaluator:
  param:
    hd_dim: 4000
    # npe1: 214
    # npe2: 60
    reram_size: 256
    # f1: 200
    # d1: 128
    # kron: false
    frequency: 1e8
    out_channels_1: 64
    kernel_size_1: 7
    stride_1: 2
    padding_1: 0
    dilation_1: 1
    cnn_x_dim_1: 8
    cnn_y_dim_1: 8
    out_channels_2: 64
    kernel_size_2: 3
    stride_2: 1
    padding_2: 0
    dilation_2: 1
    cnn_x_dim_2: 4
    cnn_y_dim_2: 4
    encoder_x_dim: 8
    encoder_y_dim: 8
    inner_dim: 4092

plot_param:
  var_param:
    hd_dim:
      - 512
      - 1024
      - 2048
      - 3072
      - 4096
      - 5120
      - 6144
      - 7168
      - 8192
    d1:
      - 32
      - 32
      - 64
      - 64
      - 64
      - 64
      - 64
      - 64
      - 64

data_collect:
  output_file: hdnn-pim.csv # absolute path if from checkpoint